# Site settings
title: Mariana Blog
SEOTitle: Mariana Blog
header-img: /dev.azure.com/HealMSlin/8544be09-1224-4eb0-824b-90c4ec9d49ee/_apis/git/repositories/7a27a721-4c93-4ecf-8258-d5422217b60a/items?path=%2F1621390631325_3901.png&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=octetStream&api-version=5.0
email: HealMSlin@gmail.com
description: "write less, do more"
keyword: "Lin,Mariana Blog, Denislin的博客, front-end, full-stack, 前端"
url: "http://mariana-yui.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mariana-yui/mariana-yui.github.io.git" # you code repository

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Sometimes you have to stop thinking too much and just go where your heart takes you."
sidebar-avatar: https://dev.azure.com/HealMSlin/8544be09-1224-4eb0-824b-90c4ec9d49ee/_apis/git/repositories/7a27a721-4c93-4ecf-8258-d5422217b60a/items?path=%2F1621390655047_8325.png&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=octetStream&api-version=5.0 # use absolute URL, seeing it's used in both `/` and `/about/`

# bgm
aplayer_js: https://mariana-yui.github.io/js/APlayer.min.js

# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
github_username: Mariana-Yui
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]
plugins:
  - jekyll-paginate

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true #是否开启Gitalk评论
  clientID: 2109c781e4ec5e2e16bc #生成的clientID
  clientSecret: ebdb76ce92d1167556fa1cc15634cc2819faa04a #生成的clientSecret
  repo: mariana-yui.github.io #仓库名称
  owner: mariana-yui #github用户名
  admin: mariana-yui
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 8fd9faeb30a21f9c4295bc1446138fc2

# Google Analytics
ga_track_id: "UA-148995736-1" # Format: UA-xxxxxx-xx
ga_domain: auto # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 0 # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
